# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofs < Formula
  desc "A lightweight, fast HTTP file server written in Go"
  homepage "https://github.com/samzong/gofs"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/gofs/releases/download/v0.3.0/gofs_Darwin_x86_64.tar.gz"
      sha256 "5be4fc569b6e4e41c543c430a7ef76244b51dcdf2ee2a43530c6831058481ca1"

      def install
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/gofs/releases/download/v0.3.0/gofs_Darwin_arm64.tar.gz"
      sha256 "bd8efa21abae1ae12123c8f92ede61a50bec7732571428d67b891ab8628de4c9"

      def install
        bin.install "gofs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.3.0/gofs_Linux_x86_64.tar.gz"
      sha256 "fd21d119e2d6350e8bdbcc734232f3afc160ae02d9ce873652e251ad9f940026"
      def install
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.3.0/gofs_Linux_arm64.tar.gz"
      sha256 "8551fe30abe131a46a944026fa524122ff21babbdae0be2b8deac0e6ecab1e22"
      def install
        bin.install "gofs"
      end
    end
  end

  test do
    system "#{bin}/gofs", "--version"
  end
end
