# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofs < Formula
  desc "A lightweight, fast HTTP file server written in Go"
  homepage "https://github.com/samzong/gofs"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/gofs/releases/download/v0.4.0/gofs_Darwin_x86_64.tar.gz"
      sha256 "bd7bb309ed71e4ade6d473e699ddfcb5cab2ad594ca6565a4ad15a29aba39117"

      define_method(:install) do
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/gofs/releases/download/v0.4.0/gofs_Darwin_arm64.tar.gz"
      sha256 "ea33fd3373b491b27294db36b83a77bdc947bdfa49a3811afc7b060aec3adf96"

      define_method(:install) do
        bin.install "gofs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.4.0/gofs_Linux_x86_64.tar.gz"
      sha256 "3c3a362668f29eebbdb29a3c3035f7bef3fb484b25444819394c5af877615e71"
      define_method(:install) do
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.4.0/gofs_Linux_arm64.tar.gz"
      sha256 "0916fee717badeee09eaefc4c7a51aba53f2940aeddfff0729d3f75fa4f51d27"
      define_method(:install) do
        bin.install "gofs"
      end
    end
  end

  test do
    system "#{bin}/gofs", "--version"
  end
end
