# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofs < Formula
  desc "A lightweight, fast HTTP file server written in Go"
  homepage "https://github.com/samzong/gofs"
  version "0.2.6-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/gofs/releases/download/v0.2.6-test/gofs_Darwin_x86_64.tar.gz"
      sha256 "6fa0375bb963405c2701b2054a850a332c6e6817917159cb4dc02e43314e872b"

      def install
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/gofs/releases/download/v0.2.6-test/gofs_Darwin_arm64.tar.gz"
      sha256 "6c7ca392174651c552f5773e5210d74ce002bae241a6f67146e3e966c64b98f8"

      def install
        bin.install "gofs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.2.6-test/gofs_Linux_x86_64.tar.gz"
      sha256 "6e26636fdaacc9986b1620d84864a736bb2bad2de4001b9753ff8e684f871c6f"
      def install
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.2.6-test/gofs_Linux_arm64.tar.gz"
      sha256 "2830b072f87f67273319685cf1d3f5d86d1acbfb8bbd347499bab1362663610a"
      def install
        bin.install "gofs"
      end
    end
  end

  test do
    system "#{bin}/gofs", "--version"
  end
end
