# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofs < Formula
  desc "A lightweight, fast HTTP file server written in Go"
  homepage "https://github.com/samzong/gofs"
  version "0.2.5-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/gofs/releases/download/v0.2.5-test/gofs_Darwin_x86_64.tar.gz"
      sha256 "d1b9150fd01e208d5d7b7660f4695bf72241e781045ac21d05b59304f0263dd6"

      def install
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/gofs/releases/download/v0.2.5-test/gofs_Darwin_arm64.tar.gz"
      sha256 "3d37696fbda09d60eddb5868f9685b293cf9bea1ed9500a717c0b02bbc2e16a6"

      def install
        bin.install "gofs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.2.5-test/gofs_Linux_x86_64.tar.gz"
      sha256 "2f0150bda7ad43f96b3dc8330285df7657b87bc3a80a7fdbb48a1a2d33080a30"
      def install
        bin.install "gofs"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/gofs/releases/download/v0.2.5-test/gofs_Linux_arm64.tar.gz"
      sha256 "f1154123bd3f1e8f615ca9ba934e7f17b2c9b326ca79bc8f5913e3b1108f42fb"
      def install
        bin.install "gofs"
      end
    end
  end

  test do
    system "#{bin}/gofs", "--version"
  end
end
