# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirrormate < Formula
  desc "One-shot mirror injection for Docker builds and compose workflows."
  homepage "https://github.com/samzong/mirrormate"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.4/mirrormate_Darwin_x86_64.tar.gz"
      sha256 "9e822c2a75f4283c67e38fcc0e6993333d8bdca531f46523f6fe665e5bf0111b"

      def install
        bin.install "mirrormate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.4/mirrormate_Darwin_arm64.tar.gz"
      sha256 "5570a811a6b734be22643d64db33f1aca2abc4357f3248cd246e9962f95c1f74"

      def install
        bin.install "mirrormate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.4/mirrormate_Linux_x86_64.tar.gz"
      sha256 "f1bbd1587640583f59dc1aa632bb663e77fbf0a3dda4edaac85b7a556fde6985"
      def install
        bin.install "mirrormate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.4/mirrormate_Linux_arm64.tar.gz"
      sha256 "418600fb25629e3039dbb364664187e43228fdc548d1b63f8296af70b32adc96"
      def install
        bin.install "mirrormate"
      end
    end
  end
end
