# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirrormate < Formula
  desc "One-shot mirror injection for Docker builds and compose workflows."
  homepage "https://github.com/samzong/mirrormate"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.6/mirrormate_Darwin_x86_64.tar.gz"
      sha256 "e9dde08b28f7e696c0771ba4918b6de71e8bb780fe1bdcefe9dbc7316e17baef"

      def install
        bin.install "mirrormate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.6/mirrormate_Darwin_arm64.tar.gz"
      sha256 "d7ba07ef6a339320fe46c84f5d113e48f318712a297f046d57349580a6269789"

      def install
        bin.install "mirrormate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.6/mirrormate_Linux_x86_64.tar.gz"
      sha256 "5be3ebd29722aeca9db488374dbaf8c1646793c042eaeceaedd0c6df8adc576a"
      def install
        bin.install "mirrormate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.6/mirrormate_Linux_arm64.tar.gz"
      sha256 "ba3ea07f3ddb4ef6d4ae56daee42c633f32d20efcb1d48135e1a40764e68f7b1"
      def install
        bin.install "mirrormate"
      end
    end
  end
end
