# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirrormate < Formula
  desc "One-shot mirror injection for Docker builds and compose workflows."
  homepage "https://github.com/samzong/mirrormate"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.2/mirrormate_Darwin_x86_64.tar.gz"
      sha256 "6ffe0d875b37c957abc5b979345eb5005ebad1a6159b55762e1e0837b1a647b8"

      def install
        bin.install "mirrormate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.2/mirrormate_Darwin_arm64.tar.gz"
      sha256 "970e4b61ba47dfaad3c43fa5225467c673ba6f9455aaa591baf35fce32cbb5ba"

      def install
        bin.install "mirrormate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.2/mirrormate_Linux_x86_64.tar.gz"
      sha256 "92c7cc7fb508d0d9abf2a5b28b20b10636356b547675cf271bfd5fcd202cdd74"
      def install
        bin.install "mirrormate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samzong/mirrormate/releases/download/v0.0.2/mirrormate_Linux_arm64.tar.gz"
      sha256 "38c3e369a48725fe1a9726d9c1979e87b5b042d499175920cdd1d9488b59c594"
      def install
        bin.install "mirrormate"
      end
    end
  end
end
